automount-open.desktop                       usr/share/@CODENAME_SAFE@-cinnamon-settings/
cinnamon-background-properties/*.xml         usr/share/cinnamon-background-properties/
schemas/installed/*.gschema.override         usr/share/glib-2.0/schemas
etc                                          usr/share/@CODENAME_SAFE@-cinnamon-settings/
usr                                          usr/share/@CODENAME_SAFE@-cinnamon-settings/
